version: '2'
services:
  flipdot-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flipdot-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - "TZ=America/Chicago"
    volumes:
      - ./config.ini:/app/config.ini
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped
